import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { zhCN } from "@clerk/localizations";

import { cn } from "@/lib/utils";
import Providers from "@/components/query-provider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Task",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider
			localization={zhCN}
			appearance={{
				variables: {
					fontSize: "16px",
				},
			}}
		>
			<html lang="en">
				<body className={cn(inter.className, "antialiased min-h-screen")}>
					<Toaster />
					<Providers>{children}</Providers>
				</body>
			</html>
		</ClerkProvider>
	);
}
